<a href="https://colab.research.google.com/github/LeafarxC/aula_dados_analytics_python/blob/main/arrays_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Para criar um array numpy utilizamos a função array() - Essa função cria um array a partir de uma lista

array1 = np.array([1,2,3])
print(array1)
print(type(array1))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#Arrays de 2 dimensões (Também conhecido como matriz)
array2 = np.array([[1,2,3],[4,5,6]])
print(array2)

[[1 2 3]
 [4 5 6]]


In [5]:
#Arrays de 3 dimensões
array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
#Criando um array com N dimensões

array4 = np.array([1,2,3], ndmin=5)
print(array4)

[[[[[1 2 3]]]]]


In [7]:
#Verificando o número de dimensões de um array
print(array1.ndim)
print(array2.ndim)
print(array4.ndim)

1
2
5


# NP Arange - Arrays com Intervalo Definido
Similar à função range() do Python, np.arange() cria arrays com valores dentro de um intervalo especificado.

In [8]:
# Criando um array de 0 a 20
array5 = np.arange(21)
print(array5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [9]:
# Criando um array de 2 a 10 com passo de 2
array6 = np.arange(2,11,2)
print(array6)

[ 2  4  6  8 10]


# Arrays com Espaçamento Uniforme
np.linspace() cria arrays com um número específico de elementos igualmente espaçados dentro de um intervalo.

In [11]:
# Criando um array com 5 elementos entre 0 e 10 (inclusive)
array7 = np.linspace(0,100,5)
print(array7)

[  0.  25.  50.  75. 100.]


In [12]:
# Exemplo com mais elementos
array8 = np.linspace(1,2,10)
print(array8)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


# Arrays de Zeros
Cria um array preenchido com zeros. Útil para inicializar arrays.

In [13]:
# Criando um array 1D de 5 zeros
array9 = np.zeros(5)
print(array9)

[0. 0. 0. 0. 0.]


In [14]:
# Criando um array 2D (3 linhas, 4 colunas) de zeros
array10 = np.zeros((3,4))
print(array10)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Arrays de Uns
Similar a np.zeros(), cria um array preenchido com uns.

In [15]:
# Criando um array 1D de 4 uns
array11 = np.ones(4)
print(array11)

[1. 1. 1. 1.]


In [16]:
# Criando um array 2D (2 linhas, 3 colunas) de uns
array12 = np.ones((2,3))
print(array12)

[[1. 1. 1.]
 [1. 1. 1.]]
