<a href="https://colab.research.google.com/github/LeafarxC/aula_dados_analytics_python/blob/main/atributos_de_array_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atributos de um Array NumPy
Os arrays NumPy possuem vários atributos que fornecem informações sobre sua estrutura e dados.

# dtype: Tipo de Dado dos Elementos
Indica o tipo de dado dos elementos armazenados no array (e.g., int64, float64).

In [2]:
import numpy as np

In [4]:
#Array int
array1 = np.array([5, 17, 32, -50])
print(array1)
print(array1.dtype)

[  5  17  32 -50]
int64


In [6]:
#Array float
array_float = np.array([1, 1.5, 3.4, -17, -3.2])
print(array_float)
print(array_float.dtype)

[  1.    1.5   3.4 -17.   -3.2]
float64


In [8]:

#Array booleano
arr_bool = np.array([True, False, True])
print(arr_bool)
print(arr_bool.dtype)

[ True False  True]
bool


In [9]:
#Array string
array_str = np.array(['Python', 'Java', 'C++'])
print(array_str)
print(array_str.dtype)

['Python' 'Java' 'C++']
<U6


# shape: Formato do Array
Retorna uma tupla indicando o número de elementos em cada dimensão.

In [10]:
array_1dim = np.array([10, 43, 22])
print(array_1dim)
print(array_1dim.shape)

[10 43 22]
(3,)


In [11]:
matriz = np.array([[10, 49, 37], [-13, -9, -15]])
print(matriz)
print(matriz.shape)

[[ 10  49  37]
 [-13  -9 -15]]
(2, 3)


# size: Número Total de Elementos
Retorna o número total de elementos no array.

In [14]:
matriz2 = np.array([[10, 49, 37], [-13, -9, -15]])
print(matriz2.size)

6


In [15]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("Size de arr_1d:", arr_1d.size)

Size de arr_1d: 5


# ndim: Número de Dimensões
Retorna o número de dimensões (eixos) do array. É o mesmo que a dimensão do array, conforme vimos anteriormente.

In [16]:
array_1d = np.array([2.3, 2.5, 9.7])
print(array_1d.ndim)

1


In [17]:
matriz = np.array([[10, 49, 37], [-13, -9, -15]])
print(matriz.ndim)

2


# Conversões de Arrays
Você pode converter o tipo de dado de um array usando o método .astype().

In [19]:
array_float = np.array([1, 1.5, 3.4, -17, -3.2])
print(array_float)
print(array_float.dtype)

#cast
array_cast = array_float.astype(int)
print(array_cast)
print(array_cast.dtype)


[  1.    1.5   3.4 -17.   -3.2]
float64
[  1   1   3 -17  -3]
int64


In [20]:
# Convertendo para float
arr3 = np.array([1, 2, 3])

print(arr3)
print(arr3.dtype)

arr4 = arr3.astype(float)
print(arr4)
print(arr4.dtype)

[1 2 3]
int64
[1. 2. 3.]
float64
