<a href="https://colab.research.google.com/github/LeafarxC/aula_dados_analytics_python/blob/main/combinacao_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Combinação e Divisão de Arrays
NumPy oferece diversas funções para combinar e dividir arrays, o que é fundamental para manipular conjuntos de dados maiores ou reestruturá-los para análises específicas.

# vstack() e hstack(): Empilhamento Vertical e Horizontal
Essas funções são usadas para empilhar arrays ao longo de um eixo específico:

np.vstack() (Vertical Stack): Empilha arrays verticalmente (ao longo das linhas). Os arrays devem ter o mesmo número de colunas. np.hstack() (Horizontal Stack): Empilha arrays horizontalmente (ao longo das colunas). Os arrays devem ter o mesmo número de linhas.

In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Empilhamento Vertical (vstack)
# Cria um array 2x3 a partir de dois arrays 1x3
vertical_stack = np.vstack((arr1, arr2))
print("Empilhamento Vertical (vstack):\n", vertical_stack)


matriz1 = np.array([[10, 20],
                    [30, 40]])
matriz2 = np.array([[50, 60],
                    [70, 80]])

# Empilhamento Vertical de matrizes
vertical_stack_matrix = np.vstack((matriz1, matriz2))
print("\nEmpilhamento Vertical de Matrizes:\n", vertical_stack_matrix)



# Empilhamento Horizontal (hstack)
# Cria um array 1x6 a partir de dois arrays 1x3
horizontal_stack = np.hstack((arr1, arr2))
print("\nEmpilhamento Horizontal (hstack):\n", horizontal_stack)


# Empilhamento Horizontal de matrizes
horizontal_stack_matrix = np.hstack((matriz1, matriz2))
print("\nEmpilhamento Horizontal de Matrizes:\n", horizontal_stack_matrix)


Empilhamento Vertical (vstack):
 [[1 2 3]
 [4 5 6]]

Empilhamento Vertical de Matrizes:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]

Empilhamento Horizontal (hstack):
 [1 2 3 4 5 6]

Empilhamento Horizontal de Matrizes:
 [[10 20 50 60]
 [30 40 70 80]]


# concatenate() e stack(): Funções Mais Gerais de Combinação
Estas são funções mais flexíveis para combinar arrays:

np.concatenate(): Concatena arrays ao longo de um eixo existente. É mais geral que vstack e hstack (que são, na verdade, wrappers para concatenate). Os arrays devem ter o mesmo shape em todos os eixos, exceto no eixo de concatenação. np.stack(): Empilha arrays ao longo de um novo eixo. Todos os arrays de entrada devem ter o mesmo shape.

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenar ao longo do eixo 0 (linhas para arrays 1D, por exemplo)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
print("Concatenar (axis=0):", concat_axis0)

matrix1 = np.array([[10, 20],
                    [30, 40]])
matrix2 = np.array([[50, 60],
                    [70, 80]])

# Concatenar matrizes ao longo do eixo 0 (linhas)
concat_matrix_axis0 = np.concatenate((matrix1, matrix2), axis=0)
print("\nConcatenar Matrizes (axis=0):\n", concat_matrix_axis0)

# Concatenar matrizes ao longo do eixo 1 (colunas)
concat_matrix_axis1 = np.concatenate((matrix1, matrix2), axis=1)
print("\nConcatenar Matrizes (axis=1):\n", concat_matrix_axis1)

# Usando np.stack() - Cria uma nova dimensão
# Para arrays 1D, np.stack cria um array 2D
stacked_arrays = np.stack((arr1, arr2))
print("\nStacking (padrão, cria novo eixo 0):\n", stacked_arrays)
print("Shape do stacked_arrays:", stacked_arrays.shape) # (2, 3)

# Stacking no eixo 1 (o novo eixo é o segundo)
stacked_arrays_axis1 = np.stack((arr1, arr2), axis=1)
print("\nStacking (axis=1):\n", stacked_arrays_axis1)
print("Shape do stacked_arrays_axis1:", stacked_arrays_axis1.shape) # (3, 2)

Concatenar (axis=0): [1 2 3 4 5 6]

Concatenar Matrizes (axis=0):
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]

Concatenar Matrizes (axis=1):
 [[10 20 50 60]
 [30 40 70 80]]

Stacking (padrão, cria novo eixo 0):
 [[1 2 3]
 [4 5 6]]
Shape do stacked_arrays: (2, 3)

Stacking (axis=1):
 [[1 4]
 [2 5]
 [3 6]]
Shape do stacked_arrays_axis1: (3, 2)


# split(), hsplit(), vsplit(): Divisão de Arrays
Estas funções são o oposto das operações de combinação, permitindo que você divida um array em múltiplos sub-arrays.

np.split(): Divide um array ao longo de um eixo especificado em vários sub-arrays. Você pode especificar o número de divisões iguais ou uma lista de índices onde a divisão deve ocorrer.
np.hsplit() (Horizontal Split): Divide um array horizontalmente (ao longo das colunas). Equivalente a np.split(array, indices_or_sections, axis=1).
np.vsplit() (Vertical Split): Divide um array verticalmente (ao longo das linhas). Equivalente a np.split(array, indices_or_sections, axis=0).

In [4]:
arr_para_dividir = np.arange(16).reshape(4, 4)
print("Array para divisão:\n", arr_para_dividir)

Array para divisão:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
# Divisão Vertical (vsplit) - Divide em 2 partes iguais
# Note que o número de divisões deve ser um divisor do número de linhas
v_split_arrays = np.vsplit(arr_para_dividir, 2)
print("\nDivisão Vertical (vsplit em 2):\n", v_split_arrays)
print("Primeira parte:\n", v_split_arrays[0])
print("Segunda parte:\n", v_split_arrays[1])


Divisão Vertical (vsplit em 2):
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
Primeira parte:
 [[0 1 2 3]
 [4 5 6 7]]
Segunda parte:
 [[ 8  9 10 11]
 [12 13 14 15]]


In [6]:
# Divisão Horizontal (hsplit) - Divide em 4 partes iguais
# Note que o número de divisões deve ser um divisor do número de colunas
h_split_arrays = np.hsplit(arr_para_dividir, 4)
print("\nDivisão Horizontal (hsplit em 4):\n", h_split_arrays)
print("Primeira parte (coluna 0):\n", h_split_arrays[0])
print("Última parte (coluna 3):\n", h_split_arrays[3])


Divisão Horizontal (hsplit em 4):
 [array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
Primeira parte (coluna 0):
 [[ 0]
 [ 4]
 [ 8]
 [12]]
Última parte (coluna 3):
 [[ 3]
 [ 7]
 [11]
 [15]]


In [8]:
# Usando np.split() para uma divisão mais genérica
arr_1d_split = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("\nArray 1D para split:", arr_1d_split)

# Dividir em 4 partes iguais
split_equal = np.split(arr_1d_split, 4)
print("Split em 4 partes iguais:", split_equal)




Array 1D para split: [10 20 30 40 50 60 70 80]
Split em 4 partes iguais: [array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]


In [9]:
# Dividir em pontos específicos (índices 2 e 5)
split_at_indices = np.split(arr_1d_split, [2, 5])
print("Split em índices [2, 5]:", split_at_indices)

# Split de matriz ao longo de um eixo específico
matrix_split = np.arange(20).reshape(4, 5)
print("\nMatriz para split genérico:\n", matrix_split)

Split em índices [2, 5]: [array([10, 20]), array([30, 40, 50]), array([60, 70, 80])]

Matriz para split genérico:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [10]:
# Dividir a matriz em 2 partes ao longo do eixo 0 (linhas)
split_matrix_axis0 = np.split(matrix_split, 2, axis=0)
print("\nSplit da matriz (axis=0):\n", split_matrix_axis0)

# Dividir a matriz em 5 partes ao longo do eixo 1 (colunas)
split_matrix_axis1 = np.split(matrix_split, 5, axis=1)
print("\nSplit da matriz (axis=1):\n", split_matrix_axis1)



Split da matriz (axis=0):
 [array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])]

Split da matriz (axis=1):
 [array([[ 0],
       [ 5],
       [10],
       [15]]), array([[ 1],
       [ 6],
       [11],
       [16]]), array([[ 2],
       [ 7],
       [12],
       [17]]), array([[ 3],
       [ 8],
       [13],
       [18]]), array([[ 4],
       [ 9],
       [14],
       [19]])]


# Combinação e Particionamento
O uso conjunto dessas funções de combinação e divisão permite manipular os dados de forma muito flexível. Por exemplo, você pode particionar um dataset para treinamento e teste, ou combinar resultados de diferentes processamentos.

In [11]:
# Criando dois datasets "simulados"
dataset_parte1 = np.random.rand(5, 3) # 5 amostras, 3 características
dataset_parte2 = np.random.rand(7, 3) # 7 amostras, 3 características

print("Dataset Parte 1 (shape):", dataset_parte1.shape)
print("Dataset Parte 2 (shape):", dataset_parte2.shape)

# Combinando os datasets verticalmente (assumindo que representam mais amostras)
full_dataset = np.vstack((dataset_parte1, dataset_parte2))
print("\nDataset Completo (vstack) shape:", full_dataset.shape)

# Particionando o dataset completo em treino e teste (exemplo simples)
# Vamos dividir em 10 linhas para treino e 2 para teste
train_data, test_data = np.vsplit(full_dataset, [10])

print("\nDados de Treino shape:", train_data.shape)
print("Dados de Teste shape:", test_data.shape)

# Outro exemplo: combinando características
features_a = np.array([[1, 2], [3, 4]])
features_b = np.array([[5, 6], [7, 8]])

# Combinando características horizontalmente
combined_features = np.hstack((features_a, features_b))
print("\nCaracterísticas Combinadas (hstack):\n", combined_features)

Dataset Parte 1 (shape): (5, 3)
Dataset Parte 2 (shape): (7, 3)

Dataset Completo (vstack) shape: (12, 3)

Dados de Treino shape: (10, 3)
Dados de Teste shape: (2, 3)

Características Combinadas (hstack):
 [[1 2 5 6]
 [3 4 7 8]]
