<a href="https://colab.research.google.com/github/LeafarxC/aula_dados_analytics_python/blob/main/indexacao_fatiamernto_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Indexação e Fatiamento
A indexação e o fatiamento são operações cruciais para acessar e manipular subconjuntos de dados dentro dos arrays NumPy.



# Acessando Elementos

Você pode acessar elementos individuais de um array usando colchetes [] e especificando o índice. Lembre-se que a indexação em Python (e NumPy) começa em 0.

In [2]:
# Array 1D
arr_1d = np.array([10, 20, 30, 40, 50])
print("Array 1D:", arr_1d)

# Acessando o primeiro elemento (índice 0)
print("Primeiro elemento:", arr_1d[0])

# Acessando o terceiro elemento (índice 2)
print("Terceiro elemento:", arr_1d[2])

# Acessando o último elemento (índice -1)
print("Último elemento:", arr_1d[-1])

# Array 2D (Matriz)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nMatriz:\n", matrix)

# Acessando um elemento na matriz: [linha, coluna]
# Acessando o elemento na primeira linha, segunda coluna (valor 2)
print("Elemento [0, 1]:", matrix[0, 1])

# Acessando o elemento na segunda linha, terceira coluna (valor 6)
print("Elemento [1, 2]:", matrix[1, 2])

Array 1D: [10 20 30 40 50]
Primeiro elemento: 10
Terceiro elemento: 30
Último elemento: 50

Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento [0, 1]: 2
Elemento [1, 2]: 6


# Fatiamento (Slicing)
O fatiamento permite que você extraia sub-arrays (partes) de um array existente. A sintaxe básica é [start:stop:step].

start: O índice inicial (inclusive). Se omitido, assume 0. stop: O índice final (exclusive). Se omitido, assume o final do array. step: O passo (salto) entre os índices. Se omitido, assume 1.

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Array original:", arr)

# Fatiando do índice 2 ao 5 (exclusive)
fat1 = arr[2:6]
print("Fatiamento [2:6]:", fat1)

# Fatiando do início ao índice 4 (exclusive)
fat2 = arr[:5]
print("Fatiamento [:5]:", fat2)

# Fatiando do índice 5 ao final
fat3 = arr[5:]
print("Fatiamento [5:]:", fat3)

# Fatiando com passo: do início ao fim, pulando de 2 em 2
fat4 = arr[::2]
print("Fatiamento [::2]:", fat4)

# Fatiamento em arrays 2D (Matrizes)
matriz = np.array([[10, 20, 30, 40],
                   [50, 60, 70, 80],
                   [90, 100, 110, 120]])
print("\nMatriz:\n", matriz)

# Acessando todas as linhas, mas apenas as colunas 1 e 2
fat1 = matrix[:, 1:3]
print("Fatiamento da matriz (todas as linhas, colunas 1 e 2):\n", fat1)

# Acessando as duas primeiras linhas e todas as colunas
fat2 = matrix[0:2, :]
print("Fatiamento da matriz (duas primeiras linhas, todas as colunas):\n", fat2)

# Acessando uma sub-matriz específica (linhas 0 e 1, colunas 0 e 1)
fat3 = matrix[0:2, 0:2]
print("Fatiamento da matriz (linhas 0 e 1, colunas 0 e 1):\n", fat3)


Array original: [0 1 2 3 4 5 6 7 8 9]
Fatiamento [2:6]: [2 3 4 5]
Fatiamento [:5]: [0 1 2 3 4]
Fatiamento [5:]: [5 6 7 8 9]
Fatiamento [::2]: [0 2 4 6 8]

Matriz:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Fatiamento da matriz (todas as linhas, colunas 1 e 2):
 [[2 3]
 [5 6]
 [8 9]]
Fatiamento da matriz (duas primeiras linhas, todas as colunas):
 [[1 2 3]
 [4 5 6]]
Fatiamento da matriz (linhas 0 e 1, colunas 0 e 1):
 [[1 2]
 [4 5]]
