<a href="https://colab.research.google.com/github/LeafarxC/aula_dados_analytics_python/blob/main/manipulacao_de_formas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulação de Formas (Shapes)
A manipulação da forma (shape) de um array é uma operação fundamental no NumPy, permitindo que você reestruture seus dados sem alterá-los. Isso é muito comum em tarefas de Machine Learning e Deep Learning.

# reshape(): Reformatando Arrays
A função reshape() permite que você altere a forma de um array, desde que o novo shape tenha o mesmo número total de elementos que o original. Você pode usar -1 em uma das dimensões para que o NumPy calcule automaticamente o tamanho dessa dimensão.

In [2]:
import numpy as np

In [8]:
# Array 1D com 12 elementos
arr_original = np.arange(12)
print("Array original:", arr_original)
print("Shape original:", arr_original.shape)

# Remodelando para uma matriz 3 linhas e 4 colunas
matriz_3x4 = arr_original.reshape(3, 4)
print("\nMatriz 3x4:\n", matriz_3x4)
print("Shape da matriz 3x4:", matriz_3x4.shape)

# Remodelando para uma matriz 4 linhas e 3 colunas
matriz_4x3 = arr_original.reshape(4, 3)
print("\nMatriz 4x3:\n", matriz_4x3)
print("Shape da matriz 4x3:", matriz_4x3.shape)

# Usando -1 para que o NumPy calcule a dimensão
# Remodelando para 2 linhas e o NumPy calcula as colunas (2x6)
matrix_2x_neg1 = arr_original.reshape(2, -1)
print("\nMatriz 2x(-1):\n", matrix_2x_neg1)


# Remodelando para 3 dimensões (2x2x3)
arr_3_dim = arr_original.reshape(2, 2, 3)
print("\nArray 2x2x3:", arr_3_dim)


Array original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape original: (12,)

Matriz 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape da matriz 3x4: (3, 4)

Matriz 4x3:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape da matriz 4x3: (4, 3)

Matriz 2x(-1):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Array 2x2x3: [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


# newaxis, expand_dims, squeeze: Adicionando e Removendo Dimensões
Essas ferramentas são essenciais para ajustar as dimensões de um array, especialmente quando você precisa que ele se adeque aos requisitos de entrada de certas funções ou modelos.

np.newaxis: Uma constante que, quando usada na indexação, adiciona uma nova dimensão ao array.
np.expand_dims(): Uma função que explicitamente adiciona uma nova dimensão em um eixo específico.
np.squeeze(): Remove dimensões que têm apenas um elemento (dimensões "redundantes").

In [4]:
arr = np.array([1, 2, 3, 4])
print("Array original:", arr)
print("Shape original:", arr.shape) # (4,)

# Adicionando uma nova dimensão usando newaxis
# Transforma um vetor linha em uma matriz coluna (4, -> 4,1)
arr_coluna = arr[:, np.newaxis]
print("\nArray como coluna (newaxis):\n", arr_coluna)
print("Shape do array como coluna:", arr_coluna.shape) # (4, 1)

# Transforma um vetor coluna em uma matriz linha (4, -> 1,4)
arr_linha = arr[np.newaxis, :]
print("\nArray como linha (newaxis):\n", arr_linha)
print("Shape do array como linha:", arr_linha.shape) # (1, 4)

# Adicionando uma nova dimensão usando np.expand_dims()
# Adiciona dimensão no eixo 0 (início)
arr_expanded_0 = np.expand_dims(arr, axis=0)
print("\nArray expandido no eixo 0:\n", arr_expanded_0)
print("Shape do array expandido no eixo 0:", arr_expanded_0.shape) # (1, 4)

# Adiciona dimensão no eixo 1 (depois da primeira dimensão)
arr_expanded_1 = np.expand_dims(arr, axis=1)
print("\nArray expandido no eixo 1:\n", arr_expanded_1)
print("Shape do array expandido no eixo 1:", arr_expanded_1.shape) # (4, 1)

# Removendo dimensões com np.squeeze()
arr_com_dimensoes_redundantes = np.array([[[1, 2, 3]]])
print("\nArray com dimensões redundantes:\n", arr_com_dimensoes_redundantes)
print("Shape do array com redundância:", arr_com_dimensoes_redundantes.shape) # (1, 1, 3)

arr_squeezed = np.squeeze(arr_com_dimensoes_redundantes)
print("Array após squeeze:\n", arr_squeezed)
print("Shape do array após squeeze:", arr_squeezed.shape) # (3,)

Array original: [1 2 3 4]
Shape original: (4,)

Array como coluna (newaxis):
 [[1]
 [2]
 [3]
 [4]]
Shape do array como coluna: (4, 1)

Array como linha (newaxis):
 [[1 2 3 4]]
Shape do array como linha: (1, 4)

Array expandido no eixo 0:
 [[1 2 3 4]]
Shape do array expandido no eixo 0: (1, 4)

Array expandido no eixo 1:
 [[1]
 [2]
 [3]
 [4]]
Shape do array expandido no eixo 1: (4, 1)

Array com dimensões redundantes:
 [[[1 2 3]]]
Shape do array com redundância: (1, 1, 3)
Array após squeeze:
 [1 2 3]
Shape do array após squeeze: (3,)


# Transposição de Arrays (.T)
A transposição é uma operação que inverte as dimensões de um array, ou seja, as linhas se tornam colunas e as colunas se tornam linhas. Para matrizes 2D, isso significa que o elemento na posição [i, j] se move para [j, i]. Para arrays de dimensões mais altas, a transposição inverte a ordem dos eixos.

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matriz original:\n", matrix)
print("Shape da matriz original:", matrix.shape) # (2, 3)

# Transpondo a matriz usando .T
matrix_transposed = matrix.T
print("\nMatriz transposta:\n", matrix_transposed)
print("Shape da matriz transposta:", matrix_transposed.shape) # (3, 2)

# Exemplo com tensor 3D
tensor = np.arange(24).reshape(2, 3, 4)
print("\nTensor original (2x3x4):\n", tensor)
print("Shape do tensor original:", tensor.shape)

# Transpondo o tensor
# A transposição reverte a ordem dos eixos
tensor_transposed = tensor.T
print("\nTensor transposto (4x3x2):\n", tensor_transposed)
print("Shape do tensor transposto:", tensor_transposed.shape)

# flatten() vs. ravel(): Achatar Arrays
Ambos os métodos são usados para "achatar" um array em uma única dimensão (1D). A principal diferença reside na forma como lidam com a memória:

flatten(): Sempre retorna uma cópia do array original. Modificações no array resultante não afetam o original. ravel(): Retorna uma visão do array original sempre que possível (se os dados forem contíguos na memória). Se os dados não forem contíguos, ele pode retornar uma cópia. Modificações na visão afetam o array original. Geralmente é mais eficiente se você não precisa de uma cópia independente.

In [9]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matriz original:\n", matrix)

# Usando flatten() - retorna uma CÓPIA
flattened_copy = matrix.flatten()
print("\nArray achatado com flatten():", flattened_copy)
flattened_copy[0] = 99 # Modificando a cópia
print("Flattened copy após modificação:", flattened_copy)
print("Matriz original após modificar a cópia (sem alteração):\n", matrix)

# Usando ravel() - retorna uma VISÃO (se possível)
raveled_view = matrix.ravel()
print("\nArray achatado com ravel():", raveled_view)
raveled_view[0] = 88 # Modificando a visão
print("Raveled view após modificação:", raveled_view)
print("Matriz original após modificar a visão (alterada):\n", matrix)

# Resetando a matriz para o próximo exemplo
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Verificando se ravel() retornou uma visão
# Em muitos casos, is not None resultará em True, mas pode ser False se uma cópia for feita
# Se o array original for modificado através da vista, é uma vista.
is_view = raveled_view.base is not None and raveled_view.base is matrix
print(f"\nravel() retornou uma visão? {is_view}") # Deve ser True neste caso

Matriz original:
 [[1 2 3]
 [4 5 6]]

Array achatado com flatten(): [1 2 3 4 5 6]
Flattened copy após modificação: [99  2  3  4  5  6]
Matriz original após modificar a cópia (sem alteração):
 [[1 2 3]
 [4 5 6]]

Array achatado com ravel(): [1 2 3 4 5 6]
Raveled view após modificação: [88  2  3  4  5  6]
Matriz original após modificar a visão (alterada):
 [[88  2  3]
 [ 4  5  6]]

ravel() retornou uma visão? False
