<a href="https://colab.research.google.com/github/LeafarxC/aula_dados_analytics_python/blob/main/operacoes_arrays_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operações Elementares (Aritméticas)
As operações aritméticas com arrays NumPy são realizadas elemento a elemento.

In [1]:
import numpy as np

In [3]:
arr1 = np.arange(1, 5)
arr2 = np.arange(5, 9)

print(arr1)
print(arr2)

# Soma
soma = arr1 + arr2
print("Soma:", soma)

# Subtração
subtracao = arr2 - arr1
print("Subtração:", subtracao)

# Multiplicação (elemento a elemento)
multiplicacao = arr1 * arr2
print("Multiplicação (elemento a elemento):", multiplicacao)

# Divisão (elemento a elemento)
divisao = arr2 / arr1
print("Divisão (elemento a elemento):", divisao)

# Potência
potencia = arr1 ** 2
print("Potência (arr1 ao quadrado):", potencia)

[1 2 3 4]
[5 6 7 8]
Soma: [ 6  8 10 12]
Subtração: [4 4 4 4]
Multiplicação (elemento a elemento): [ 5 12 21 32]
Divisão (elemento a elemento): [5.         3.         2.33333333 2.        ]
Potência (arr1 ao quadrado): [ 1  4  9 16]


# Operações com Escalar
Quando você realiza uma operação entre um array e um valor escalar (um único número), o NumPy aplica essa operação a cada elemento do array.

In [5]:
array = np.array([10, 20, 30, 40, 50, 60])
numero = 5

# Soma com escalar
soma = array + numero
print(soma)

# Multiplicação com escalar
multi = array * numero
print(multi)

[15 25 35 45 55 65]
[ 50 100 150 200 250 300]


# Broadcasting
Broadcasting é a capacidade do NumPy de tratar arrays com diferentes shapes durante operações aritméticas. Ele permite que arrays menores sejam "esticados" para combinar com o shape de arrays maiores, de modo que a operação elemento a elemento possa ser realizada.

In [9]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print(array1)
print(array1.shape)


array2 = np.array([10, 20, 30])
print(array2)
print(array2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[10 20 30]
(3,)


In [10]:
# array2 é "broadcast" para corresponder ao número de linhas de array1
# [10, 20, 30]
# [10, 20, 30]
resultado_broadcasting = array1 + array2
print("Resultado do Broadcasting:\n", resultado_broadcasting)

# Outro exemplo de broadcasting
arr_c = np.array([[100],
                  [200]]) # Shape (2, 1)

resultado_broadcasting_2 = array1 + arr_c
print("Resultado do Broadcasting 2:\n", resultado_broadcasting_2)

Resultado do Broadcasting:
 [[11 22 33]
 [14 25 36]]
Resultado do Broadcasting 2:
 [[101 102 103]
 [204 205 206]]
